<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="methods" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" parallel="methods" name="Test(failed)">
    <classes>
      <class name="Actitime.testscript.CustomerCreation">
        <methods>
          <include name="login"/>
          <include name="logout"/>
          <include name="closeBrowser"/>
          <include name="launchBrowser"/>
          <include name="createCustomer"/>
        </methods>
      </class> <!-- Actitime.testscript.CustomerCreation -->
      <class name="Actitime.testscript.DropdownHandle">
        <methods>
          <include name="DDhandle"/>
          <include name="login"/>
          <include name="logout"/>
          <include name="closeBrowser"/>
          <include name="launchBrowser"/>
        </methods>
      </class> <!-- Actitime.testscript.DropdownHandle -->
      <class name="Actitime.testscript.AlertHandling_work_excel">
        <methods>
          <include name="logout"/>
          <include name="closeBrowser"/>
          <include name="login"/>
          <include name="launchBrowser"/>
          <include name="AlertHandle"/>
        </methods>
      </class> <!-- Actitime.testscript.AlertHandling_work_excel -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
